name: UXJEHLER
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60259
title: Joseph Ehler - UX/UI Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9efef'
    - '#152121'
    - '#5b646e'
    - '#bcc0c3'
    - '#95938e'
  brandStrength: 0
  lightness: 0.3717733030207455
  saturation: 0.5946014449000359
  rhythmicContrast: 0.7659712468739599
purpose: []
