name: UXJEHLER
favicon: null
layout_spectrum: 0.5789493655320257
typography_spectrum: 0.1143206034321338
title: Joseph Ehler - UX/UI Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9944596700370312
  lightness: 0.3717733030207455
  saturation: 0.5946014449000359
  rhythmicContrast: 0.7659712468739599
purpose: []
