name: UXJEHLER
favicon: null
layout_spectrum: 0.60367
typography_spectrum: 0.58756
title: Joseph Ehler - UX/UI Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9dfc1'
    - '#f3b8a9'
    - '#e4677d'
    - '#d3444c'
    - '#aa8893'
  brandStrength: 1
  lightness: 0.3717733030207455
  saturation: 0.5946014449000359
  rhythmicContrast: 0.7659712468739599
purpose: []
